# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0
# SPDX-License-Identifier: MIT

name: precommit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@2cbe15e8b03a049a30e364c16cde78038c443eda # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@2cbe15e8b03a049a30e364c16cde78038c443eda # develop
